"""Generate the ICLR 2027 paper's tables from committed data files.

Every table under ``results/tables/`` is a pure function of:

* ``analysis/run_tree_aggregate_2026-09-06.csv``  (``tools/aggregate.py --csv``
  on HPC; frozen 100-episode official evaluations with ``full_reset``),
* ``results/random-eval/<game>-masked/eval_episodes.jsonl`` (uniform-policy floor),
* ``analysis/probe_refit.csv`` and ``analysis/probe_refit.md`` (corrected probes),
* ``results/dynamics_probe/scored/competence_table.csv`` (rollout and
  counterfactual probes on the warm seed-0 checkpoints).

Re-run after the run tree changes::

    python scripts/build_iclr_tables.py

Numbers in the paper's prose are checked against these files by hand; the
tables themselves are never retyped.
"""
from __future__ import annotations

import csv
import json
import math
import re
import statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGG = ROOT / "analysis" / "run_tree_aggregate_2026-09-06.csv"
PROBE_CSV = ROOT / "analysis" / "probe_refit.csv"
PROBE_MD = ROOT / "analysis" / "probe_refit.md"
COMP = ROOT / "results" / "dynamics_probe" / "scored" / "competence_table.csv"
RANDOM_DIR = ROOT / "results" / "random-eval"
OUT = ROOT / "results" / "tables"

STUDY = ["vc33", "sb26", "cd82", "tn36", "ls20", "lf52"]
ALL25 = sorted("ar25 bp35 cd82 cn04 dc22 ft09 g50t ka59 lf52 lp85 ls20 m0r0 r11l re86 "
               "s5i5 sb26 sc25 sk48 sp80 su15 tn36 tr87 tu93 vc33 wa30".split())
HEADER = "% GENERATED by scripts/build_iclr_tables.py. Do not edit by hand.\n"


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n <= 0:
        return (0.0, 0.0)
    p = k / n
    den = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / den
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return (max(centre - half, 0.0), min(centre + half, 1.0))


def load_agg() -> list[dict]:
    rows = []
    with open(AGG, newline="") as f:
        for r in csv.DictReader(f):
            if r["done"] != "True" or r["e100_n"] in ("", "0"):
                continue
            r["seed"] = int(r["seed"])
            for k in ("e100_clear_rate", "e100_official", "e100_official_mean",
                      "norm_entropy", "image_loss"):
                r[k] = float(r[k]) if r[k] not in ("", "nan") else float("nan")
            r["e100_n"] = int(r["e100_n"])
            r["e100_levels_max"] = int(r["e100_levels_max"])
            r["train_clears"] = int(r["train_clears"]) if r["train_clears"] else 0
            r["train_eps"] = int(r["train_eps"]) if r["train_eps"] else 0
            rows.append(r)
    return rows


def cells(rows, batch, arm, game):
    out = [r for r in rows if r["batch"] in batch and r["arm"] == arm and r["game"] == game]
    return sorted(out, key=lambda r: r["seed"])


def stock(rows, game):
    """Stock DreamerV3: paired cold (seeds 2-4) for the study games, sweep cold otherwise."""
    return cells(rows, {"paired"} if game in STUDY else {"sweep"}, "cold", game)


def fmt_rate(c):
    return f"{c['e100_clear_rate']:.2f}".replace("0.", ".") if c["e100_clear_rate"] < 1 else "1.00"


def fmt_off(x):
    return f"{x:.4f}"


def random_floor() -> dict[str, dict]:
    from arc3_wm import official_rhae as O  # noqa: WPS433 (needs the venv)
    out = {}
    for d in sorted(RANDOM_DIR.glob("*-masked")):
        game = d.name.split("-")[0]
        eps = [json.loads(l)["rewards"] for l in open(d / "eval_episodes.jsonl") if l.strip()]
        b = O.load_official_baselines(game, ROOT / "environment_files")
        res = O.compute_official_rhae(episodes_rewards=eps, game_id=game, baselines=b)
        key = [k for k in res if "per_game" in k][0]
        out[game] = {"n": len(eps), "clears": sum(1 for e in eps if any(r > 0 for r in e)),
                     "official": float(res[key])}
    return out


# ---------------------------------------------------------------- main table
def table_main(rows, floor):
    lines = [HEADER, r"\begin{tabular}{l ccc c c cc}", r"\toprule",
             r" & \multicolumn{3}{c}{Stock DreamerV3, 3 seeds} & Random floor & & \multicolumn{2}{c}{PPO flat, 2 seeds} \\",
             r"\cmidrule(lr){2-4}\cmidrule(lr){5-5}\cmidrule(lr){7-8}",
             r"Game & clear rate per seed & official & levels & official (clears/300) & entropy & clear rate & official \\",
             r"\midrule"]
    scorers = [g for g in ALL25 if any(c["e100_official"] > 0 for c in stock(rows, g))]
    zeros = [g for g in ALL25 if g not in scorers]
    for g in scorers + ["__sep__"] + STUDY_ZERO_ORDER(zeros):
        if g == "__sep__":
            lines.append(r"\midrule")
            continue
        cs = stock(rows, g)
        rates = ", ".join(fmt_rate(c) for c in cs)
        off = statistics.mean(c["e100_official"] for c in cs)
        lev = max(c["e100_levels_max"] for c in cs)
        ent = statistics.mean(c["norm_entropy"] for c in cs)
        fl = floor.get(g)
        fl_s = (f"{fl['official']:.4f}" if fl['official'] >= 5e-5 else f"{fl['official']:.0e}") + f" ({fl['clears']}/{fl['n']})" if fl else "--"
        ppo = cells(rows, {"ppo"}, "flat", g)
        ppo_r = ", ".join(fmt_rate(c) for c in ppo) if ppo else "--"
        ppo_o = ", ".join(fmt_off(c["e100_official"]) for c in ppo) if ppo else "--"
        bold = (lambda s: r"\textbf{" + s + "}") if off > 0 else (lambda s: s)
        lines.append(f"\\texttt{{{g}}} & {rates} & {bold(fmt_off(off))} & {lev} & {fl_s} & {ent:.3f} & {ppo_r} & {ppo_o} \\\\")
    mean25 = statistics.mean(statistics.mean(c["e100_official"] for c in stock(rows, g)) for g in ALL25)
    lines += [r"\midrule",
              f"Mean over 25 games & & {mean25:.4f} & & & & & \\\\",
              r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n", mean25, scorers


def STUDY_ZERO_ORDER(zeros):
    """Study games first among the zeros, then the rest alphabetically."""
    return [g for g in STUDY if g in zeros] + [g for g in zeros if g not in STUDY]


# ---------------------------------------------------------------- compact table
def table_compact(rows, floor):
    """Body table: the four scorers plus the six study games, stock only."""
    games = [g for g in ALL25 if any(c["e100_official"] > 0 for c in stock(rows, g))]
    games += [g for g in STUDY if g not in games]
    lines = [HEADER, r"\begin{tabular}{l ccc cc}", r"\toprule",
             r"Game & Clear rate per seed & Official RHAE & Levels & Norm.\ entropy & Random floor (clears/300) \\",
             r"\midrule"]
    for g in games:
        cs = stock(rows, g)
        rates = ", ".join(fmt_rate(c) for c in cs)
        off = statistics.mean(c["e100_official"] for c in cs)
        lev = max(c["e100_levels_max"] for c in cs)
        ent = statistics.mean(c["norm_entropy"] for c in cs)
        fl = floor.get(g)
        fl_s = (f"{fl['official']:.4f}" if fl['official'] >= 5e-5 else f"{fl['official']:.0e}") + f" ({fl['clears']})" if fl else "--"
        o = (r"\textbf{" + fmt_off(off) + "}") if off > 0 else fmt_off(off)
        lines.append(f"\\texttt{{{g}}} & {rates} & {o} & {lev} & {ent:.3f} & {fl_s} \\\\")
    n_other = 25 - len(games)
    lines += [r"\midrule",
              f"Other {n_other} games & 0 on every seed & 0.0000 & 0 & 1.000 & -- \\\\",
              r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- ladder
LADDER = [
    ("Stock DreamerV3", ("paired", "sweep"), "cold", "nothing"),
    ("State-change bonus, $\\beta{=}0.1$", ("shape01",), "cold", "reward contact"),
    ("State-change bonus, $\\beta{=}0.01$", ("shape001",), "cold", "reward contact"),
    ("Type-balanced prior", ("mixture",), "cold", "a prior over action types"),
    ("PPO, factored head$^{\\dagger}$", ("ppo",), "factored", "a factored action head"),
]
LADDER_GAMES = ["cd82", "vc33", "ls20", "sp80", "sb26", "tn36", "lf52"]


def table_ladder(rows):
    """Games as rows, interventions as columns; cell = seeds scoring, pooled clear rate, official."""
    lines = [HEADER, r"\begin{tabular}{l" + "c" * len(LADDER) + "}", r"\toprule",
             "Game & " + " & ".join(label for label, *_ in LADDER) + r" \\",
             " & " + " & ".join(f"\\emph{{{restores}}}" for *_, restores in LADDER) + r" \\",
             r"\midrule"]
    for g in LADDER_GAMES:
        vals = []
        for label, batches, arm, restores in LADDER:
            cs = cells(rows, set(batches), arm, g)
            if not cs:
                vals.append("--")
                continue
            k = sum(1 for c in cs if c["e100_official"] > 0)
            pooled = sum(round(c["e100_clear_rate"] * c["e100_n"]) for c in cs)
            n = sum(c["e100_n"] for c in cs)
            off = statistics.mean(c["e100_official"] for c in cs)
            lev = max(c["e100_levels_max"] for c in cs)
            s = f"{k}/{len(cs)}, {pooled / n:.2f}, {off:.3f}"
            if lev >= 2:
                s += f", L{lev}"
            vals.append((r"\textbf{" + s + "}") if k > 0 else s)
        lines.append(f"\\texttt{{{g}}} & " + " & ".join(vals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- compute
def table_compute(rows):
    games = ["cd82", "sb26", "vc33"]
    lines = [HEADER, r"\begin{tabular}{l ccc}", r"\toprule",
             r"Game & 500k steps (3 seeds) & 5M steps (1 seed) & Update ratio 512 (2 seeds) \\",
             r"\midrule"]
    for g in games:
        def cell(cs):
            if not cs:
                return "--"
            rates = ", ".join(fmt_rate(c) for c in cs)
            off = statistics.mean(c["e100_official"] for c in cs)
            lev = max(c["e100_levels_max"] for c in cs)
            return f"{rates} ({off:.4f}, L{lev})"
        lines.append(f"\\texttt{{{g}}} & {cell(stock(rows, g))} & {cell(cells(rows, {'long5m'}, 'cold', g))} & {cell(cells(rows, {'ratio512'}, 'cold', g))} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- probes
def load_probe_md():
    """Paired latent minus pixel differences with CI, from the generated markdown."""
    diffs = {}
    pat = re.compile(r"^\| (\w+) \| (\w+) \| [\d.]+ \| ([\d.]+)\*? \| ([\d.]+)\*? \| ([\d.]+)\*? \| ([+-][\d.]+) \[([+-][\d.]+), ([+-][\d.]+)\]( \(ns\))? \|")
    for line in open(PROBE_MD, encoding="utf-8"):
        m = pat.match(line.strip())
        if m:
            g, t, lat, pix, clk, d, lo, hi, ns = m.groups()
            diffs[(g, t)] = dict(d=float(d), lo=float(lo), hi=float(hi), ns=bool(ns))
    return diffs


def load_probe_csv():
    acc = {}
    with open(PROBE_CSV, newline="") as f:
        for r in csv.DictReader(f):
            acc[(r["game"], r["feature"], r["target"])] = (float(r["balanced_acc"]), r["decodable"] == "True")
    return acc


def star(v, dec):
    return f"{v:.2f}" + ("$^{*}$" if dec else "")


def table_probes(acc, diffs):
    lines = [HEADER, r"\begin{tabular}{l c ccc c ccc c}", r"\toprule",
             r" & & \multicolumn{4}{c}{Level identity} & \multicolumn{4}{c}{Reward proximity} \\",
             r"\cmidrule(lr){3-6}\cmidrule(lr){7-10}",
             r"Game & chance & latent & pixel & clock & latent$-$pixel [95\% CI] & latent & pixel & clock & latent$-$pixel [95\% CI] \\",
             r"\midrule"]
    chance = {"cd82": 1 / 6, "lf52": 1 / 10, "ls20": 1 / 7, "sb26": 1 / 8, "tn36": 1 / 7, "vc33": 1 / 7}
    for g in STUDY:
        def trip(t):
            l, ld = acc[(g, "both", t)]
            p, pd = acc[(g, "pixel", t)]
            c, cd = acc[(g, "clock", t)]
            dd = diffs[(g, t)]
            ci = f"{dd['d']:+.2f} [{dd['lo']:+.2f}, {dd['hi']:+.2f}]"
            if not dd["ns"]:
                ci = r"\textbf{" + ci + "}"
            return f"{star(l, ld)} & {star(p, pd)} & {star(c, cd)} & {ci}"
        lines.append(f"\\texttt{{{g}}} & {chance[g]:.2f} & {trip('level_id')} & {trip('reward_proximity')} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- scorecard
def table_scorecard(rows, acc, diffs):
    comp = {}
    with open(COMP, newline="") as f:
        for r in csv.DictReader(f):
            if r["source"] == "human":
                comp[r["game"]] = r
    lines = [HEADER, r"\begin{tabular}{l c c cc cc c c}", r"\toprule",
             r" & & recon.\ & \multicolumn{2}{c}{open-loop rollout} & \multicolumn{2}{c}{action-conditioning} & level id & reward prox. \\",
             r"\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
             r"Game & RHAE & loss & $\Delta$ vs copy, $h{=}1$ & $\Delta$ vs copy, $H{=}8$ & sensitivity & beats copy & latent$-$pixel & latent$-$pixel \\",
             r"\midrule"]
    for g in STUDY:
        cs = stock(rows, g)
        off = statistics.mean(c["e100_official"] for c in cs)
        recon = statistics.mean(c["image_loss"] for c in cs)
        c = comp[g]
        sens = f"{100 * float(c['sensitivity']):.1f}\\%" if c["sensitivity"] else "--"
        beats = f"{100 * float(c['beats_copy_frac']):.1f}\\%" if c["beats_copy_frac"] else "--"
        lid = diffs[(g, "level_id")]
        rp = diffs[(g, "reward_proximity")]
        def mark(dd):
            s = f"{dd['d']:+.2f}"
            return s if dd["ns"] else (r"\textbf{" + s + "}")
        o = (r"\textbf{" + fmt_off(off) + "}") if off > 0 else fmt_off(off)
        lines.append(f"\\texttt{{{g}}} & {o} & {recon:.2f} & {float(c['delta_1']):+.3f} & {float(c['delta_H']):+.3f} & {sens} & {beats} & {mark(lid)} & {mark(rp)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- full 25 appendix
def table_full25(rows):
    lines = [HEADER, r"\begin{tabular}{l c cc cc c c}", r"\toprule",
             r"Game & seeds & clear rate per seed & official per seed & train clears / episodes & norm.\ entropy & image loss & levels \\",
             r"\midrule"]
    for g in ALL25:
        cs = stock(rows, g)
        seeds = ",".join(str(c["seed"]) for c in cs)
        rates = ", ".join(fmt_rate(c) for c in cs)
        offs = ", ".join(fmt_off(c["e100_official"]) for c in cs)
        tr = ", ".join(f"{c['train_clears']}/{c['train_eps']}" for c in cs)
        ent = ", ".join(f"{c['norm_entropy']:.3f}" for c in cs)
        il = ", ".join(f"{c['image_loss']:.2f}" for c in cs)
        lev = max(c["e100_levels_max"] for c in cs)
        lines.append(f"\\texttt{{{g}}} & {seeds} & {rates} & {offs} & {tr} & {ent} & {il} & {lev} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- ladder appendix (per seed)
def table_ladder_full(rows):
    """Two tabulars (left, right) so the per-seed listing fits one page side by side."""
    arms = [("Bonus $\\beta{=}0.1$", "shape01", "cold"), ("Bonus $\\beta{=}0.01$", "shape001", "cold"),
            ("Type-balanced prior", "mixture", "cold"), ("5M steps", "long5m", "cold"),
            ("Update ratio 512", "ratio512", "cold"), ("PPO flat$^{\\dagger}$", "ppo", "flat"),
            ("PPO factored$^{\\dagger}$", "ppo", "factored")]
    body = []
    for label, batch, arm in arms:
        rs = sorted([r for r in rows if r["batch"] == batch and r["arm"] == arm], key=lambda r: (r["game"], r["seed"]))
        body.append(f"\\multicolumn{{5}}{{l}}{{\\emph{{{label}}}}} \\\\")
        for c in rs:
            k = round(c["e100_clear_rate"] * c["e100_n"])
            lo, hi = wilson(k, c["e100_n"])
            body.append(f"\\texttt{{{c['game']}}} & {c['seed']} & {c['e100_clear_rate']:.2f} [{lo:.2f}, {hi:.2f}] & {fmt_off(c['e100_official'])} & {c['e100_levels_max']} \\\\")
        body.append(r"\addlinespace[1pt]")
    half = (len(body) + 1) // 2
    head = [r"\begin{tabular}{lc c c c}", r"\toprule",
            r"Game & seed & clear rate [95\% CI] & official & levels \\", r"\midrule"]
    tail = [r"\bottomrule", r"\end{tabular}"]
    left = "\n".join(head + body[:half] + tail)
    right = "\n".join(head + body[half:] + tail)
    return HEADER + "\\begin{minipage}[t]{0.49\\linewidth}\\centering\n" + left + "\n\\end{minipage}\\hfill\n\\begin{minipage}[t]{0.49\\linewidth}\\centering\n" + right + "\n\\end{minipage}\n"


# ---------------------------------------------------------------- warm vs cold appendix
def table_warmcold(rows):
    lines = [HEADER, r"\begin{tabular}{l cc cc}", r"\toprule",
             r" & \multicolumn{2}{c}{Cold} & \multicolumn{2}{c}{Warm (25-game pretrained)} \\",
             r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
             r"Game & clear rate per seed & official & clear rate per seed & official \\", r"\midrule"]
    for g in STUDY:
        c = cells(rows, {"paired"}, "cold", g)
        w = cells(rows, {"paired"}, "warm", g)
        def s(cs):
            if not cs:
                return "-- & --"
            return ", ".join(fmt_rate(x) for x in cs) + " & " + fmt_off(statistics.mean(x["e100_official"] for x in cs)) + f" ({len(cs)} seeds)"
        lines.append(f"\\texttt{{{g}}} & {s(c)} & {s(w)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- random floor, both arms
def table_floor():
    from arc3_wm import official_rhae as O
    lines = [HEADER, r"\begin{tabular}{l cc cc cc}", r"\toprule",
             r" & \multicolumn{2}{c}{masked} & \multicolumn{2}{c}{unmasked} & \multicolumn{2}{c}{episode length} \\",
             r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
             r"Game & clears/300 & official & clears/300 & official & masked & unmasked \\", r"\midrule"]
    games = sorted({d.name.split("-")[0] for d in RANDOM_DIR.glob("*-masked")})
    for g in games:
        cells_ = []
        lens = []
        for arm in ("masked", "unmasked"):
            d = RANDOM_DIR / f"{g}-{arm}"
            eps = [json.loads(l)["rewards"] for l in open(d / "eval_episodes.jsonl") if l.strip()]
            b = O.load_official_baselines(g, ROOT / "environment_files")
            res = O.compute_official_rhae(episodes_rewards=eps, game_id=g, baselines=b)
            key = [k for k in res if "per_game" in k][0]
            off = float(res[key])
            clears = sum(1 for e in eps if any(r > 0 for r in e))
            cells_.append(f"{clears} & " + (f"{off:.4f}" if off >= 5e-5 or off == 0 else f"{off:.0e}"))
            lens.append(statistics.mean(len(e) for e in eps))
        lines.append(f"\\texttt{{{g}}} & " + " & ".join(cells_) + f" & {lens[0]:.0f} & {lens[1]:.0f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- entropy vs score scatter
def scatter_csv(rows):
    out = ROOT / "paper" / "iclr-2027" / "curves" / "entropy_vs_score.csv"
    with open(out, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["game", "seed", "entropy", "official", "clear_rate", "scorer"])
        for g in ALL25:
            for c in stock(rows, g):
                w.writerow([g, c["seed"], f"{c['norm_entropy']:.4f}", f"{c['e100_official']:.5f}",
                            f"{c['e100_clear_rate']:.2f}", int(c["e100_official"] > 0)])


# ---------------------------------------------------------------- full probe table (appendix)
def table_probes_full(acc, diffs):
    targets = [("level_id", "level identity"), ("transition", "level transition"),
               ("reward_imminence", "reward within 5"), ("reward_proximity", "reward within 10"),
               ("time_since_reset", "elapsed time")]
    lines = [HEADER, r"\begin{tabular}{ll c ccc c}", r"\toprule",
             r"Game & Target & chance & latent & pixel & clock & latent$-$pixel [95\% CI] \\", r"\midrule"]
    chance = {"level_id": {"cd82": 1 / 6, "lf52": 1 / 10, "ls20": 1 / 7, "sb26": 1 / 8, "tn36": 1 / 7, "vc33": 1 / 7},
              "transition": 0.5, "reward_imminence": 0.5, "reward_proximity": 0.5, "time_since_reset": 0.2}
    for g in STUDY:
        first = True
        for t, name in targets:
            l, ld = acc[(g, "both", t)]
            p, pd = acc[(g, "pixel", t)]
            c, cd = acc[(g, "clock", t)]
            ch = chance[t][g] if isinstance(chance[t], dict) else chance[t]
            dd = diffs.get((g, t))
            ci = "--" if dd is None else f"{dd['d']:+.2f} [{dd['lo']:+.2f}, {dd['hi']:+.2f}]" + ("" if dd["ns"] else "")
            if dd is not None and not dd["ns"]:
                ci = r"\textbf{" + ci + "}"
            lines.append(f"{'\\texttt{' + g + '}' if first else ''} & {name} & {ch:.2f} & {star(l, ld)} & {star(p, pd)} & {star(c, cd)} & {ci} \\\\")
            first = False
        lines.append(r"\addlinespace[2pt]")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def lf52_stats():
    """Macros and point files for the lf52 episode-length figure, from the
    authoritative ``analysis/lf52_episode_lengths.csv`` (one row per episode,
    RHAE action-count convention, phantom 0-action resets flagged)."""
    import io
    cur = ROOT / "paper" / "iclr-2027" / "curves"
    src = ROOT / "analysis" / "lf52_episode_lengths.csv"
    lines = [l for l in open(src) if not l.startswith("#")]
    rows = list(csv.DictReader(io.StringIO("".join(lines))))
    human = [r for r in rows if r["series"] == "human" and r["is_phantom"] == "0"]
    agent = [r for r in rows if r["series"] != "human"]
    hs = sorted(int(r["action_count"]) for r in human)
    wins = sorted(int(r["action_count"]) for r in human if r["terminal_state"] == "WIN")
    others = sorted(int(r["action_count"]) for r in human if r["terminal_state"] != "WIN")
    gameovers = sum(1 for r in human if r["terminal_state"] == "GAME_OVER")
    ag = sorted(int(r["action_count"]) for r in agent)
    q1, med, q3 = hs[len(hs) // 4], hs[len(hs) // 2], hs[3 * len(hs) // 4]
    with open(cur / "lf52_wins.csv", "w", newline="") as f:
        w = csv.writer(f); w.writerow(["length"]); w.writerows([[l] for l in wins])
    with open(cur / "lf52_others.csv", "w", newline="") as f:
        w = csv.writer(f); w.writerow(["length"]); w.writerows([[l] for l in others])
    out = [HEADER,
           f"\\newcommand{{\\lfHumanN}}{{{len(hs)}}}", f"\\newcommand{{\\lfHumanMin}}{{{hs[0]}}}",
           f"\\newcommand{{\\lfHumanQone}}{{{q1}}}", f"\\newcommand{{\\lfHumanMed}}{{{med}}}",
           f"\\newcommand{{\\lfHumanQthree}}{{{q3}}}", f"\\newcommand{{\\lfHumanMax}}{{{hs[-1]}}}",
           f"\\newcommand{{\\lfHumanWins}}{{{len(wins)}}}", f"\\newcommand{{\\lfHumanGameovers}}{{{gameovers}}}",
           f"\\newcommand{{\\lfAgentN}}{{{len(ag)}}}", f"\\newcommand{{\\lfAgentMin}}{{{ag[0]}}}",
           f"\\newcommand{{\\lfAgentMax}}{{{ag[-1]}}}"]
    return "\n".join(out) + "\n"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rows = load_agg()
    floor = random_floor()
    acc = load_probe_csv()
    diffs = load_probe_md()
    (OUT / "floor.tex").write_text(table_floor())
    (OUT / "probes_full.tex").write_text(table_probes_full(acc, diffs))
    scatter_csv(rows)
    (OUT / "lf52_stats.tex").write_text(lf52_stats())
    main_tex, mean25, scorers = table_main(rows, floor)
    (OUT / "main25.tex").write_text(main_tex)
    (OUT / "compact.tex").write_text(table_compact(rows, floor))
    (OUT / "ladder.tex").write_text(table_ladder(rows))
    (OUT / "compute.tex").write_text(table_compute(rows))
    (OUT / "probes.tex").write_text(table_probes(acc, diffs))
    (OUT / "scorecard.tex").write_text(table_scorecard(rows, acc, diffs))
    (OUT / "full25.tex").write_text(table_full25(rows))
    (OUT / "ladder_full.tex").write_text(table_ladder_full(rows))
    (OUT / "warmcold.tex").write_text(table_warmcold(rows))
    # numbers the prose quotes, for checking
    summary = {
        "mean25_official": mean25,
        "scorers": scorers,
        "floor": floor,
        "stock": {g: [(c["seed"], c["e100_clear_rate"], c["e100_official"], c["e100_levels_max"], c["norm_entropy"], c["train_clears"], c["train_eps"]) for c in stock(rows, g)] for g in ALL25},
    }
    (OUT / "numbers.json").write_text(json.dumps(summary, indent=1))
    print(f"mean over 25: {mean25:.5f}; scorers: {scorers}")
    print("wrote", sorted(p.name for p in OUT.iterdir()))


if __name__ == "__main__":
    main()
